<?php

namespace Database\Seeders;
use App\Models\Product;
use App\Models\Country;
use App\Models\Category;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = Category::all()->keyBy('name'); // 'Drinks', 'Snacks', 'Sweets', 'Fruits'
        $countries = Country::all()->keyBy('name');
        
        $drinks = [
            [
                'name' => 'Coca Cola',
                'name_tm' => 'Koka-Kola',
                'name_ru' => 'Кока-Кола',
                'category' => 'Drinks',
                'country' => 'USA',
                'description' => 'Refreshing soft drink',
                'description_tm' => 'Gazlandyrylan sowuk içgi',
                'description_ru' => 'Освежающий напиток',
                'price' => 5.0,
                'is_discount' => true,
                'discount_percent' => 10,
                'image' => 'img/Coca-Cola.jpg',
                'is_new' => true,
                'is_stock' => true,
            ],
            [
                'name' => 'Pepsi',
                'name_tm' => 'Pepsi',
                'name_ru' => 'Пепси',
                'category' => 'Drinks',
                'country' => 'USA',
                'description' => 'Refreshing soft drink',
                'description_tm' => 'Gazlandyrylan sowuk içgi',
                'description_ru' => 'Освежающий напиток',
                'price' => 8.0,
                'is_discount' => false,
                'discount_percent' => 0,
                'image' => 'img/Pepsi.jpg',
                'is_new' => false,
                'is_stock' => true,
            ],
            [
                'name' => 'Lipton Tea',
                'name_tm' => 'Lipton Çaýy',
                'name_ru' => 'Липтон Чай',
                'category' => 'Drinks',
                'country' => 'UK',
                'description' => 'Refreshing soft drink',
                'description_tm' => 'Gazlandyrylan sowuk içgi',
                'description_ru' => 'Освежающий напиток',
                'price' => 7.0,
                'is_discount' => false,
                'discount_percent' => 0,
                'image' => 'img/Lipton Tea.jpg',
                'is_new' => false,
                'is_stock' => true,
            ],
            [
                'name' => 'Apple Juice',
                'name_tm' => 'Alma Şiresi',
                'name_ru' => 'Яблочный сок',
                'category' => 'Drinks',
                'country' => 'Turkey',
                'description' => 'Refreshing soft drink',
                'description_tm' => 'Gazlandyrylan sowuk içgi',
                'description_ru' => 'Освежающий напиток',
                'price' => 15.0,
                'is_discount' => true,
                'discount_percent' => 10,
                'image' => 'img/Apple Juice.jpg',
                'is_new' => true,
                'is_stock' => true,
            ],
            [
                'name' => 'Moxito',
                'name_tm' => 'Mohito',
                'name_ru' => 'Мохито',
                'category' => 'Drinks',
                'country' => 'USA',
                'description' => 'Refreshing soft drink',
                'description_tm' => 'Gazlandyrylan sowuk içgi',
                'description_ru' => 'Освежающий напиток',
                'price' => 5.0,
                'is_discount' => true,
                'discount_percent' => 15,
                'image' => 'img/Moxito.jpg',
                'is_new' => false,
                'is_stock' => true,
            ],
            [
                'name' => 'Fanta',
                'name_tm' => 'Fanta',
                'name_ru' => 'Фанта',
                'category' => 'Drinks',
                'country' => 'USA',
                'description' => 'Refreshing soft drink',
                'description_tm' => 'Gazlandyrylan sowuk içgi',
                'description_ru' => 'Освежающий напиток',
                'price' => 6.0,
                'is_discount' => false,
                'discount_percent' => 0,
                'image' => 'img/Fanta.jpg',
                'is_new' => true,
                'is_stock' => true,
            ],
        ];
        $snacks = [
            [
                'name' => 'Pringles Chips',
                'name_tm' => 'Pringles çipsi',
                'name_ru' => 'Чипсы Принглс',
                'category' => 'Snacks',
                'country' => 'USA',
                'description' => 'Hot pepper chips',
                'description_tm' => 'Ajy burçly çips',
                'description_ru' => 'Чипсы с острым перцем',
                'price' => 35.0,
                'is_discount' => false,
                'discount_percent' => 0,
                'image' => 'img/Pringles Chips.jpg',
                'is_new' => true,
                'is_stock' => true,
            ],
            [
                'name' => 'Popcorn',
                'name_tm' => 'Popkorn',
                'name_ru' => 'Попкорн',
                'category' => 'Snacks',
                'country' => 'USA',
                'description' => 'Salted popcorn',
                'description_tm' => 'Duzly Popkorn',
                'description_ru' => 'Солёный попкорн',
                'price' => 9.0,
                'is_discount' => true,
                'discount_percent' => 10,
                'image' => 'img/Popcorn.jpg',
                'is_new' => false,
                'is_stock' => true,
            ],
            [
                'name' => 'Cheetos',
                'name_tm' => 'Çitos',
                'name_ru' => 'Читос',
                'category' => 'Snacks',
                'country' => 'USA',
                'description' => 'Crunchy cheese-flavored corn snacks',
                'description_tm' => 'Peynirli Corekli Kukruz',
                'description_ru' => 'Хрустящие кукурузные снеки со вкусом сыра',
                'price' => 20.0,
                'is_discount' => false,
                'discount_percent' => 0,
                'image' => 'img/Cheetos.jpg',
                'is_new' => false,
                'is_stock' => true,
            ],
            [
                'name' => 'Lays Chips',
                'name_tm' => 'Lays çipsi',
                'name_ru' => 'Чипсы Лейс',
                'category' => 'Snacks',
                'country' => 'USA',
                'description' => 'Crispy potato chips',
                'description_tm' => 'Çörekli kartof çips',
                'description_ru' => 'Хрустящие картофельные чипсы',
                'price' => 40.0,
                'is_discount' => true,
                'discount_percent' => 10,
                'image' => 'img/Lays Chips.jpg',
                'is_new' => true,
                'is_stock' => true,
            ],
            [
                'name' => 'Lolipop',
                'name_tm' => 'Lolipop',
                'name_ru' => 'Лолипоп',
                'category' => 'Snacks',
                'country' => 'USA',
                'description' => 'Chicken sweet',
                'description_tm' => 'Horaz Süýji',
                'description_ru' => 'сасулка',
                'price' => 3.0,
                'is_discount' => false,
                'discount_percent' => 0,
                'image' => 'img/Lolipop.jpg',
                'is_new' => true,
                'is_stock' => true,
            ],
            [
                'name' => 'Turan Chips',
                'name_tm' => 'Turan çipsi',
                'name_ru' => 'Туран Чипсы',
                'category' => 'Snacks',
                'country' => 'USA',
                'description' => 'Crispy potato chips',
                'description_tm' => 'Çörekli kartof çips',
                'description_ru' => 'Хрустящие картофельные чипсы',
                'price' => 20.0,
                'is_discount' => false,
                'discount_percent' => 0,
                'image' => 'img/Turan Chips.jpg',
                'is_new' => true,
                'is_stock' => true,
            ],
        ];

        $sweets = [
            [
                'name' => 'Chocolate Bar',
                'name_tm' => 'Şokolad',
                'name_ru' => 'Шоколад',
                'category' => 'Sweets',
                'country' => 'Russia',
                'description' => 'Delicious chocolate',
                'description_tm' => 'Tagamly şokolad',
                'description_ru' => 'Вкусный шоколад',
                'price' => 10.0,
                'is_discount' => false,
                'discount_percent' => 0,
                'image' => 'img/Chocolate Bar.jpg',
                'is_new' => false,
                'is_stock' => true,
            ],
            [
                'name' => 'KitKat',
                'name_tm' => 'KitKat',
                'name_ru' => 'КитКат',
                'category' => 'Sweets',
                'country' => 'UK',
                'description' => 'milk chocolate',
                'description_tm' => 'suytli şokolad',
                'description_ru' => 'молочный шоколад',
                'price' => 10.0,
                'is_discount' => false,
                'discount_percent' => 0,
                'image' => 'img/KitKat.jpg',
                'is_new' => true,
                'is_stock' => true,
            ],
            [
                'name' => 'Snickers',
                'name_tm' => 'Snikers',
                'name_ru' => 'Сникерс',
                'category' => 'Sweets',
                'country' => 'USA',
                'description' => 'milk chocolate',
                'description_tm' => 'suytli şokolad',
                'description_ru' => 'молочный шоколад',
                'price' => 10.0,
                'is_discount' => false,
                'discount_percent' => 0,
                'image' => 'img/Snickers.jpg',
                'is_new' => false,
                'is_stock' => true,
            ],
            [
                'name' => 'Alpen Gold',
                'name_tm' => 'Alpen Gold',
                'name_ru' => 'Альпен Голд',
                'category' => 'Sweets',
                'country' => 'Russia',
                'description' => 'milk plate',
                'description_tm' => 'suytli plitka',
                'description_ru' => 'молочная плитка',
                'price' => 17.0,
                'is_discount' => false,
                'discount_percent' => 0,
                'image' => 'img/Alpen Gold.jpg',
                'is_new' => true,
                'is_stock' => true,
            ],
            [
                'name' => 'Mars',
                'name_tm' => 'Mars',
                'name_ru' => 'марс',
                'category' => 'Sweets',
                'country' => 'Russia',
                'description' => 'milk chocolate',
                'description_tm' => 'suytli şokolad',
                'description_ru' => 'молочная шоколадка',
                'price' => 10.0,
                'is_discount' => false,
                'discount_percent' => 0,
                'image' => 'img/Mars.jpg',
                'is_new' => true,
                'is_stock' => true,
            ],
            [
                'name' => 'Kinder',
                'name_tm' => 'Kinder',
                'name_ru' => 'киндер',
                'category' => 'Sweets',
                'country' => 'Russia',
                'description' => 'milk plate',
                'description_tm' => 'suytli plitka',
                'description_ru' => 'молочная плитка',
                'price' => 17.0,
                'is_discount' => false,
                'discount_percent' => 0,
                'image' => 'img/Kinder.jpg',
                'is_new' => true,
                'is_stock' => true,
            ],
        ];

        $fruits = [
            [
                'name' => 'Apple',
                'name_tm' => 'Alma',
                'name_ru' => 'Яблоко',
                'category' => 'Fruits',
                'country' => 'Turkey',
                'description' => 'Fresh red apple',
                'description_tm' => 'Täze gyzyl alma',
                'description_ru' => 'Свежий красный яблоко',
                'price' => 3.0,
                'is_discount' => false,
                'discount_percent' => 0,
                'image' => 'img/Apple.jpg',
                'is_new' => true,
                'is_stock' => true,
            ],
            [
                'name' => 'Grape',
                'name_tm' => 'Üzüm',
                'name_ru' => 'Виноград',
                'category' => 'Fruits',
                'country' => 'Turkey',
                'description' => 'Fresh grapes',
                'description_tm' => 'Täze üzüm',
                'description_ru' => 'Свежий виноград',
                'price' => 6.0,
                'is_discount' => true,
                'discount_percent' => 10,
                'image' => 'img/Grape.jpg',
                'is_new' => false,
                'is_stock' => true,
            ],
            [
                'name' => 'Banana',
                'name_tm' => 'Banan',
                'name_ru' => 'Банан',
                'category' => 'Fruits',
                'country' => 'Turkey',
                'description' => 'Fresh Banana',
                'description_tm' => 'Täze Banan',
                'description_ru' => 'Свежий Банан',
                'price' => 20.0,
                'is_discount' => false,
                'discount_percent' => 0,
                'image' => 'img/Banana.jpg',
                'is_new' => true,
                'is_stock' => true,
            ],
            [
                'name' => 'Ananas',
                'name_tm' => 'Ananas',
                'name_ru' => 'Ананас',
                'category' => 'Fruits',
                'country' => 'Turkey',
                'description' => 'Fresh Ananas',
                'description_tm' => 'Täze Ananas',
                'description_ru' => 'Свежий Ананас',
                'price' => 30.0,
                'is_discount' => false,
                'discount_percent' => 0,
                'image' => 'img/Ananas.jpg',
                'is_new' => false,
                'is_stock' => true,
            ],
            [
                'name' => 'Cherry',
                'name_tm' => 'ulje',
                'name_ru' => 'Вишня',
                'category' => 'Fruits',
                'country' => 'Turkey',
                'description' => 'Fresh Cherry',
                'description_tm' => 'Täze Ulje',
                'description_ru' => 'Свежий Вишня',
                'price' => 27.0,
                'is_discount' => true,
                'discount_percent' => 12,
                'image' => 'img/Cherry.jpg',
                'is_new' => false,
                'is_stock' => true,
            ],
            [
                'name' => 'Lemon',
                'name_tm' => 'Limon',
                'name_ru' => 'лимон',
                'category' => 'Fruits',
                'country' => 'Turkey',
                'description' => 'Fresh Lemon',
                'description_tm' => 'Täze Limon',
                'description_ru' => 'Свежий лимон',
                'price' => 30.0,
                'is_discount' => false,
                'discount_percent' => 0,
                'image' => 'img/Ananas.jpg',
                'is_new' => false,
                'is_stock' => true,
            ],
        ];

        $allProducts = array_merge($drinks, $snacks, $sweets, $fruits);

        foreach ($allProducts as $allProduct) {
            // Category we Country ID alýar
            $category = $categories[$allProduct['category']];
            $country = $countries[$allProduct['country']];

            Product::create([
                'category_id' => $category->id,
                'country_id' => $country->id,
                'name' => $allProduct['name'],
                'name_tm' => $allProduct['name_tm'],
                'name_ru' => $allProduct['name_ru'],
                'slug' => Str::slug($allProduct['name']),
                'description' => $allProduct['description'],
                'description_tm' => $allProduct['description_tm'],
                'description_ru' => $allProduct['description_ru'],
                'price' => $allProduct['price'],
                'is_discount' => $allProduct['is_discount'],
                'discount_percent' => $allProduct['discount_percent'],
                'image' => 'img/' . Str::slug($allProduct['name']) . '.jpg',
                'is_new' => $allProduct['is_new'],
                'is_stock' => $allProduct['is_stock'],
            ]);
        }
    }
}
